jsmin.lo: /root/php-jsmin-1.0/jsmin.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/php-jsmin-1.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/php-jsmin-1.0/jsmin.c -o jsmin.lo 
$(phplibdir)/jsmin.la: ./jsmin.la
	$(LIBTOOL) --mode=install cp ./jsmin.la $(phplibdir)

./jsmin.la: $(shared_objects_jsmin) $(JSMIN_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_jsmin) $(JSMIN_SHARED_LIBADD)

